@echo off
echo Starting Road Sign Detector in DEVELOPMENT mode...
echo Activating virtual environment...
call .venv\Scripts\activate.bat

echo Setting Log Level to DEBUG...
set APP_LOG_LEVEL=DEBUG

echo Launching application...
python main.py
pause